### ISSUE TITLE
Make or find a Gratipay alternative

### ISSUE THREAD

**Issue by seanstrom** [seanstrom/planner#83]
I really want to make money, or living, from working on Open Source and Free Software.

I want to experiment with different business models for doing that. Donations being one of those models.

**Comment by chadwhitacre** [comment]
Wanna help us build Gratipay? :-)

**Comment by seanstrom** [comment]
Hey @whit537 thanks for reaching out about this. I would never have guessed that this would get on your radar. I would like to help you, but I have a few questions first. What's the actual stance Gratipay has on the whole controversy that Gittip went through. I don't want to open old wounds and pour salt, but it's an interest of mine to know. I've done my own research on the matter, but wanted your response too. If you want you can email me about it, but depending on your answer I will feel way more comfortable contributing. I hope that doesn't put you off, please understand.

**Comment by chadwhitacre** [comment]
Well, I suppose I put my foot in that one ... I'm not ready to go there. :-(

Sorry to interrupt! Best wishes! :-)

**Comment by seanstrom** [comment]
Look I understand, I'm not here to make things awkward, it's just something I would bring up since I'm aware of it and have my own set of opinions and stuff.

My other questions were going to be around what I could do to help. I'm assuming there are open issues to look at, any particular ones you care for me to look at?
